language: node_js
node_js:
- '8'
after_success:
- yarn lint || echo "Let's show the lint output here but we don't want it cause a failure yet"
- yarn report-coverage
deploy:
  provider: npm
  email: peter@terascope.io
  api_key:
    secure: "KuLX9Dws4xIS9iFwFNat0DlPWgh80sg4hc6E5Xx0MJPgf5EJSeE1HtHahpbMXzmaybfAFhCFpjaeyiLVj55DpDtASWt/KtLjT+6P9h6Z3vZJsizfPrB/vi3gubBVtk2YBkp+1xfWxxJEXpFL9e/bUa3elejKcej7dGycHqhtAumtjGNr0+6FzOzk3Ny9/VvDhlgG8sLIvvZfRw1lIKbO/rzO6jK7tcjR4jmzPaMyCuAjvsn9qy5a9LIWnITjdxsG6+0mQN9gqJDpONSwRIuPlSRM4VN+yavLslBcssEgbsl37u34ZqncgSntPbDM1KxPnWmd9hOw3rneQAef2/0DZhlqMUOuen/lODl+NukcJ/3cpFKw+Zc+C/F3Wg8Moo0DYF5G0L7OL2IXoVT2F+ye8u+mAd3D1jadzhw2+RXuSygCkwDneKbJkhBNPyTHsKUt349w5jpJSf2lQyVuI1iD5DUTQma0Su77pT41adPh+xQ3O/vHj7bCHaT8Dk4eCbFNP4FfHnO8WRE1qIcAU/nw/1NQ9qNvjbqO3bJcINi6XyFeannY0yWTB0mofglsP64gg82pxv9gWr7TIBJyyFlVJu+0X8Uq1NAt5+WAPo67lbzjvsX3SGJ3r00/wGeYnjQ/5H6MLFfF5Zene5rLVlE1rgk99+u12fGf3p4fKZkVEFY="
  on:
    branch: master
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
    repo: terascope/teraslice-client-js
